### ISSUE TITLE
Migration script unconditionally assumes that object id 4 (Server) is a blade

### ISSUE THREAD

**Issue by imriz** [device42/Racktables-to-Device42-Migration#2]
In https://github.com/device42/Racktables-to-Device42-Migration/blob/master/racktables2device42.py#L778

In RackTables, object type 4 is a server - you cannot assume that this is a blade (we tried this script and all of our servers ended up as blades).
Maybe a better idea is to only choose blade if blade_host_id is found?

**Comment by tolyadouble** [comment]
thanks for feedback, fixed
